project:
  type: website

website:
  title: "analytics_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wee-rogue
      - icon: twitter
        href: https://twitter.com/wee_rogue
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

